# Name should be aaltoapps_config.yml
development: &non_production_settings
  asi_url: "http://cos.alpha.sizl.org"
  ssl_asi_url: "https://cos.alpha.sizl.org"  # Can be same as asi_url if no https in use
  asi_url_proxied: "http://cos.alpha.sizl.org"  #this won't work completely in develpment mode
  asi_timeout: 10

  asi_app_name: aaltoapps
  asi_app_password: insert_password_here  

  consent_versions:
    fi: FI1
    en: EN1.5
    se: SE4

  email_from_address: "noreply@nowhere.test"

  # set or override Rails configuration
  rails_config:
    action_mailer:
      default_url_options:
        # options for generating urls in e-mail messages
        locale: en
        host: host_name
        # port: port_number_if_not_default
        # protocol: https  # uncomment if using https

      delivery_method: :smtp
      smtp_settings:
        address: smtp_server_address


test:
  <<: *non_production_settings

production:
  <<: *non_production_settings

  asi_url: "http://cos.alpha.sizl.org"
  ssl_asi_url: "https://cos.alpha.sizl.org"  # Can be same as asi_url if no https in use
  asi_app_name: aaltoapps
  asi_app_password: insert_password_here  
