# Name should be aaltoapps_config.yml
development: &non_production_settings
  asi_url: "http://cos.alpha.sizl.org"
  ssl_asi_url: "https://cos.alpha.sizl.org"  # Can be same as asi_url if no https in use
  asi_url_proxied: "http://cos.alpha.sizl.org"  #this won't work completely in develpment mode
  asi_timeout: 10

  asi_app_name: aaltoapps
  asi_app_password: insert_password_here  

  consent_versions:
    fi: FI1
    en: EN1.5
    se: SE4

  session_expiration: 240 # in minutes

  fallback_locale: en

  email_from_address: "noreply@nowhere.test"

  # if true new products need to be approved by an administrator
  require_approval_for_new_products: true

  # set or override Rails configuration
  rails_config:

    # delete or comment out these to disable CAS support
    rubycas:
      cas_base_url: "http://your.cas.server.example"
      proxy_callback_url: "https://callback.url.example"
      proxy_retrieval_url: "http://localhost/retrieve_pgt"

    action_mailer:
      default_url_options:
        # options for generating urls in e-mail messages
        locale: en
        host: host_name
        # port: port_number_if_not_default
        # protocol: https  # uncomment if using https

      delivery_method: :smtp
      smtp_settings:
        address: smtp_server_address


test:
  <<: *non_production_settings

production:
  <<: *non_production_settings

  asi_url: "http://cos.alpha.sizl.org"
  ssl_asi_url: "https://cos.alpha.sizl.org"  # Can be same as asi_url if no https in use
  asi_app_name: aaltoapps
  asi_app_password: insert_password_here  
